export const Config = {
  URLS: [],
  DOMAIN_URL: '',
  // BASE_URL:'https://api.safeup.co/',
  BASE_URL: 'https://api.scale-app.com/operations.php',
  SHARE_URL: 'https://api.safeup.co/safewalk.apk',
  ContentType: 'application/json',
  Accept: '',
  Version: '1.0',
  GOOGLE_MAP_KEY: 'AIzaSyBoA7DPbUr1jiq8b1-L-CLjlxyB7X54BFw',
  PRODUCTION: false,
  CORS_ANYWHERE: 'https://cors-anywhere.herokuapp.com/',

  AuthToken: '',
  FCMToken: '',
  PhoneNumber: '',
  SMSCode: '',
  Profile: null,
  Location: null,
  IsFirstRUN: true,
  IsFirstRUNasGuardian: true,
  IsSignIn: false,
  OpenStatus: '',
  Notifications: {},
};
